// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBtG59GaVlfexpC2aMTCYAoE4lGqaxDrU',
    appId: '1:586869914327:web:1bcf0a60a25de617f3ce92',
    messagingSenderId: '586869914327',
    projectId: 'intime-app-d997b',
    authDomain: 'intime-app-d997b.firebaseapp.com',
    storageBucket: 'intime-app-d997b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi_uVfzu3ogmg67y-5yDhD3jbjdwR9GsY',
    appId: '1:586869914327:android:6372423d1426def7f3ce92',
    messagingSenderId: '586869914327',
    projectId: 'intime-app-d997b',
    storageBucket: 'intime-app-d997b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3jDkWWRNb172bKTNq49AnC1B6OPL5Luo',
    appId: '1:586869914327:ios:a29165c84f6ea812f3ce92',
    messagingSenderId: '586869914327',
    projectId: 'intime-app-d997b',
    storageBucket: 'intime-app-d997b.firebasestorage.app',
    iosBundleId: 'com.jonh.intime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3jDkWWRNb172bKTNq49AnC1B6OPL5Luo',
    appId: '1:586869914327:ios:a29165c84f6ea812f3ce92',
    messagingSenderId: '586869914327',
    projectId: 'intime-app-d997b',
    storageBucket: 'intime-app-d997b.firebasestorage.app',
    iosBundleId: 'com.jonh.intime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBtG59GaVlfexpC2aMTCYAoE4lGqaxDrU',
    appId: '1:586869914327:web:608be7cd83d63340f3ce92',
    messagingSenderId: '586869914327',
    projectId: 'intime-app-d997b',
    authDomain: 'intime-app-d997b.firebaseapp.com',
    storageBucket: 'intime-app-d997b.firebasestorage.app',
  );
}
